# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exp1Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exp1Window(object):
    def setupUi(self, Exp1Window):
        Exp1Window.setObjectName("Exp1Window")
        Exp1Window.resize(400, 300)

        self.retranslateUi(Exp1Window)
        QtCore.QMetaObject.connectSlotsByName(Exp1Window)

    def retranslateUi(self, Exp1Window):
        _translate = QtCore.QCoreApplication.translate
        Exp1Window.setWindowTitle(_translate("Exp1Window", "Form"))
