# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exp2Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exp2Window(object):
    def setupUi(self, Exp2Window):
        Exp2Window.setObjectName("Exp2Window")
        Exp2Window.resize(824, 558)

        self.retranslateUi(Exp2Window)
        QtCore.QMetaObject.connectSlotsByName(Exp2Window)

    def retranslateUi(self, Exp2Window):
        _translate = QtCore.QCoreApplication.translate
        Exp2Window.setWindowTitle(_translate("Exp2Window", "Form"))
