# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exp2Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exp2Window(object):
    def setupUi(self, Exp2Window):
        Exp2Window.setObjectName("Exp2Window")
        Exp2Window.resize(923, 803)
        self.pushButton_exp2_out = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_exp2_out.setGeometry(QtCore.QRect(820, 770, 75, 23))
        self.pushButton_exp2_out.setObjectName("pushButton_exp2_out")
        self.label = QtWidgets.QLabel(Exp2Window)
        self.label.setGeometry(QtCore.QRect(30, -130, 891, 1041))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/imgs/实验2.png"))
        self.label.setObjectName("label")
        self.pushButton_q1_user = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q1_user.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.pushButton_q1_user.setObjectName("pushButton_q1_user")
        self.pushButton_q2 = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q2.setGeometry(QtCore.QRect(140, 280, 81, 31))
        self.pushButton_q2.setObjectName("pushButton_q2")
        self.pushButton_q3 = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q3.setGeometry(QtCore.QRect(140, 410, 81, 31))
        self.pushButton_q3.setObjectName("pushButton_q3")
        self.pushButton_q4 = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q4.setGeometry(QtCore.QRect(140, 500, 81, 31))
        self.pushButton_q4.setObjectName("pushButton_q4")
        self.pushButton_q5 = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q5.setGeometry(QtCore.QRect(140, 610, 81, 31))
        self.pushButton_q5.setObjectName("pushButton_q5")
        self.pushButton_q6 = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q6.setGeometry(QtCore.QRect(140, 710, 81, 31))
        self.pushButton_q6.setObjectName("pushButton_q6")
        self.pushButton_q1_random = QtWidgets.QPushButton(Exp2Window)
        self.pushButton_q1_random.setGeometry(QtCore.QRect(290, 170, 81, 31))
        self.pushButton_q1_random.setObjectName("pushButton_q1_random")
        self.label.raise_()
        self.pushButton_exp2_out.raise_()
        self.pushButton_q1_user.raise_()
        self.pushButton_q2.raise_()
        self.pushButton_q3.raise_()
        self.pushButton_q4.raise_()
        self.pushButton_q5.raise_()
        self.pushButton_q6.raise_()
        self.pushButton_q1_random.raise_()

        self.retranslateUi(Exp2Window)
        QtCore.QMetaObject.connectSlotsByName(Exp2Window)

    def retranslateUi(self, Exp2Window):
        _translate = QtCore.QCoreApplication.translate
        Exp2Window.setWindowTitle(_translate("Exp2Window", "实验2"))
        self.pushButton_exp2_out.setText(_translate("Exp2Window", "返回主窗口"))
        self.pushButton_q1_user.setText(_translate("Exp2Window", "用户输入"))
        self.pushButton_q2.setText(_translate("Exp2Window", "点击跳转"))
        self.pushButton_q3.setText(_translate("Exp2Window", "点击跳转"))
        self.pushButton_q4.setText(_translate("Exp2Window", "点击跳转"))
        self.pushButton_q5.setText(_translate("Exp2Window", "点击跳转"))
        self.pushButton_q6.setText(_translate("Exp2Window", "点击跳转"))
        self.pushButton_q1_random.setText(_translate("Exp2Window", "随机生成"))
import res_rc
